spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.mvc.routes[0].id=recommendation-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/recommendation/**

spring.cloud.gateway.mvc.routes[1].id=part-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/parsed/**,/api/scraper/**,/api/cpu/**,/api/gpu/**,/api/memory/**,/api/storage/**,/api/psu/**,/api/case/**,/api/motherboard/**,/api/market-listings/**

spring.cloud.gateway.mvc.routes[2].id=community-service
spring.cloud.gateway.mvc.routes[2].uri=lb://community-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/community/**

spring.cloud.gateway.mvc.routes[3].id=auth-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/auth/**

security.jwt.secret=your-very-long-jwt-signing-secret-key-please-change-it
auth.validate-url=http://localhost:8082/auth/validate
