
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pcbuilding
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-super-secret-key-my-super-secret-key
  expiration: 86400000
