spring.application.name=community-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/communitydb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history_community
spring.flyway.baselineOnMigrate=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
