spring.application.name=recommendation-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/pcbuilder
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history_recommendation
spring.flyway.baselineOnMigrate=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# OpenAI Configuration
openai.api-key=${OPENAI_API_KEY:}
openai.model=gpt-4o-mini
openai.url=https://api.openai.com/v1/chat/completions

# Part Service URL via Eureka
part-service.url=http://localhost:8081
