spring.datasource.url=jdbc:postgresql://localhost:5432/pcbuilder
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=part-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/