spring.datasource.url=jdbc:postgresql://localhost:5432/pcbuilder
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway migration configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history_partservice
spring.flyway.baselineOnMigrate=true
spring.flyway.out-of-order=true

spring.application.name=part-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/